### ISSUE TITLE
Using Python Alpine Docker base is bad idea

### ISSUE THREAD

**Issue by cygnusb** [Haveacry/twc3teslamate#1]
see https://pythonspeed.com/articles/alpine-docker-python/

you should switch to non-alpine based images

**Comment by cygnusb** [comment]
Thanks for implementing this. I would like to deploy evcc in the coming weeks and would also like to use the standard charging cable. Will try your implementation to get this solved.

**Comment by speedst3r** [comment]
Thanks for your suggestion. I do not agree with the blanket assertion that four year old article makes that Alpine images for Python are a bad idea. That article has cherry-picked some specific use cases and extrapolated the findings to apply to any Python workload. Let's break it down:

_1. Standard PyPI wheels don’t work on Alpine_
The Python script in this image is using binary wheels - no compilation required.

_2. Alpine builds are vastly slower, the image is bigger, and I had to do a bunch of research._
Nonsense. I have tested building this container with both 3.9-alpine and 3.9-slim. Both images took seven seconds to build on a Xeon E-2146G - no compilation of Python packages required. Similar times are seen when built with GitHub Actions. The Debian-based image came out at 148MB, the Alpine image at 70MB. The author's "bunch of research" does not match the real world output of this package. Some of the examples the author has linked to are four and six years old - much may have changed since then.

_3. Alpine Linux can cause unexpected runtime bugs._
This may be true; I can't disprove it with the operation of this image so far - though my script is very simple.

Ultimately this is a very simple use case that doesn't match with the assertions of that article - read some data from MQTT into a dictionary, format a JSON response using values from that dictionary.

If you feel passionately about using Alpine as a base image, I have added a second image build to the workflow, which you can pull with the `:debian` tag. Unlike certain EVCC contributors, I'm not going to let ideology deny requested features (control charging via vehicle API rather than local wallbox), especially when they align with the outcome of sustainably charging EVs (telling people to go buy another wallbox doesn't align with being sustainable...).
